name: 'dart_dependency_updater'
description: 'A package that will scan for dependencies in a Dart repo, update them if needed, and can update the repo with them.'
version: '1.0.22+12'
homepage: 'https://github.com/peiffer-innovations/actions_dart_dependency_updater'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  args: '^2.4.0'
  github: '^9.9.0'
  http: '^0.13.5'
  intl: '^0.18.0'
  json_class: '^2.1.5+2'
  logging: '^1.1.1'
  meta: '^1.8.0'
  pub_api_client: '^2.4.0'
  pub_semver: '^2.1.3'
  yaml: '^3.1.1'
  yaml_writer: '^1.0.3'

dev_dependencies:
  test: '^1.23.1'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
