name: 'dart_dependency_updater'
description: 'A package that will scan for dependencies in a Dart repo, update them if needed, and can update the repo with them.'
version: '1.0.22+26'
homepage: 'https://github.com/peiffer-innovations/actions_dart_dependency_updater'

environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  args: '^2.4.2'
  github: '^9.19.0'
  http: '^1.1.0'
  intl: '^0.18.1'
  json_class: '^3.0.0+4'
  logging: '^1.2.0'
  meta: '^1.9.1'
  pub_api_client: '^2.6.0'
  pub_semver: '^2.1.4'
  yaml: '^3.1.2'
  yaml_writer: '^1.0.3'

dev_dependencies: 
  test: '^1.24.6'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
