name: Automated Dependencies Updater

on:
  schedule:
    - cron: '0 1 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dependencies
        uses: peiffer-innovations/actions-dart-dependency-updater@v1.0.15
        with:
          merge: true
          pull_request: true
          token: ${{ secrets.REPO_TOKEN }}
