name: Manual Dependencies Updater

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dependencies
        uses: peiffer-innovations/action-dart-dependency-updater@v1.0.5
        with:
          merge: true
          pull_request: true
          repository: ${{ github.action_repository }}
          token: ${{ secrets.REPO_TOKEN }}
